package dev.forint.deafmute.cameraxdemo.ui

import dev.forint.deafmute.cameraxdemo.BuildConfig

data class RecognitionUiState(
    val baseUrl: String = BuildConfig.DEFAULT_API_BASE_URL,
    val authToken: String = "",
    val sessionId: String = "",
    val sessionStatus: String = "idle",
    val sessionStartedAt: String = "",
    val activeConfigName: String = "--",
    val bufferText: String = "",
    val currentGesture: String = "--",
    val displayText: String = "--",
    val outputType: String = "NONE",
    val controlAction: String = "",
    val handedness: String = "--",
    val cameraFacing: String = "back",
    val mirrored: Boolean = false,
    val inputType: String = "",
    val frameNo: Int = 0,
    val stableCount: Int = 0,
    val requiredHits: Int = 0,
    val debounced: Boolean = false,
    val detectedGestureCandidates: List<String> = emptyList(),
    val countdownMillis: Long = 0L,
    val landmarkPointCount: Int = 0,
    val supportedLandmarkGestureCodes: List<String> = emptyList(),
    val landmarkCoordinateMode: String = "",
    val landmarkOrigin: String = "",
    val landmarkOrder: String = "",
    val landmarkHandMode: String = "",
    val landmarkAssumptions: String = "",
    val latestTraceId: String = "",
    val lastMessage: String = "等待初始化",
    val isBusy: Boolean = false,
    val ttsReady: Boolean = false,
    val ttsUserStatusCode: String = "error",
    val ttsUserStatusText: String = "error（检测中）",
    val ttsProblemReason: String = "正在等待系统 TTS 初始化结果。",
    val ttsActionSuggestion: String = "如果长时间没有变化，请点“重试检测”或进入系统 TTS 设置检查引擎。",
    val ttsPhase: String = "idle",
    val ttsDefaultEngine: String = "--",
    val ttsInitStatusCode: Int? = null,
    val ttsLanguageStatusCode: Int? = null,
    val ttsInstalledEngines: List<String> = emptyList(),
    val ttsDiscoveredServices: List<String> = emptyList(),
    val ttsPendingText: String? = null,
    val ttsLastSpokenText: String? = null,
    val ttsLastError: String? = null,
    val ttsLogLines: List<String> = emptyList(),
    val errorMessage: String? = null,
    val usingFrontCamera: Boolean = false,
)
